In [120]:
import pandas as pd

### Series

In [121]:
serTest = pd.Series([10,20,'a',30,"abc",10.55])
serTest

0       10
1       20
2        a
3       30
4      abc
5    10.55
dtype: object

In [122]:
ser = pd.Series([10,20,30,40,50,])
ser

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [123]:
ser.dtype

dtype('int64')

In [124]:
serTest.values

array([10, 20, 'a', 30, 'abc', 10.55], dtype=object)

In [125]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [126]:
serTest.name = 'series'
print('Name: ',serTest.name, end='\n\n')
print(serTest)

Name:  series

0       10
1       20
2        a
3       30
4      abc
5    10.55
Name: series, dtype: object

In [127]:
print(ser[1:3])
print(ser[3])

1    20
2    30
dtype: int64
40

In [128]:
ser.iloc[[1,3,2]]

1    20
3    40
2    30
dtype: int64

In [129]:
ser.name='price'
index = pd.Series(['banana', 'mango', 'pineappl', 'apple', 'watermelon'])
ser.index = index
ser

banana        10
mango         20
pineappl      30
apple         40
watermelon    50
Name: price, dtype: int64

In [130]:
# ser.iloc['banana']  #Error
print(ser.iloc[0])
print(ser.loc['banana'])
ser.loc[['banana','apple']]

10
10

banana    10
apple     40
Name: price, dtype: int64

In [131]:
student = {
    'Vivek' : 22,
    'Bablu' : 23,
    'Anushka' : 18,
    'Shivani' : 19,
    'Viraj' : 16,
    'Shital': 18,
    'Radha' : 20,
    'Krishna' : 15
}
student

{'Vivek': 22,
 'Bablu': 23,
 'Anushka': 18,
 'Shivani': 19,
 'Viraj': 16,
 'Shital': 18,
 'Radha': 20,
 'Krishna': 15}

In [132]:
series = pd.Series(student, name = 'Age')
series

Vivek      22
Bablu      23
Anushka    18
Shivani    19
Viraj      16
Shital     18
Radha      20
Krishna    15
Name: Age, dtype: int64

In [133]:
series.index.name = 'Name'
series

Name
Vivek      22
Bablu      23
Anushka    18
Shivani    19
Viraj      16
Shital     18
Radha      20
Krishna    15
Name: Age, dtype: int64

`Conditional Operators`

In [134]:
# series>18
series[series>18]

Name
Vivek      22
Bablu      23
Shivani    19
Radha      20
Name: Age, dtype: int64

`Logical Operators`

In [135]:
series[(series>18) & (series < 20)]
# [(series>18) | (series < 20)]
# [~(series>18)]

Name
Shivani    19
Name: Age, dtype: int64

`Modifing Series`

In [136]:
series.loc[['Bablu', 'Shivani']] = [22, 18]
series

Name
Vivek      22
Bablu      22
Anushka    18
Shivani    18
Viraj      16
Shital     18
Radha      20
Krishna    15
Name: Age, dtype: int64

In [137]:
series = series.rename(index={'Anushka': 'Anu', 'Shivani': 'shiv'})
series

Name
Vivek      22
Bablu      22
Anu        18
shiv       18
Viraj      16
Shital     18
Radha      20
Krishna    15
Name: Age, dtype: int64

In [138]:
import numpy as np

s = pd.Series(['a', np.nan, 1, np.nan, np.pi, np.inf, 1.5, 2])
s.notnull().sum() # notnull function return true value for not null values and sum fuction count that vlues

6

### DataFrame

In [139]:
Data = {
    'Name' : ['Vivek', 'Bablu', 'Akbar', 'Birbal'],
    'Age' : [22,23,44,np.nan],
    'Dept' : ['cs', 'AI', 'DS', 'IT'],
    'Salary' : [80000,np.nan,50000,60000]
}

Data

{'Name': ['Vivek', 'Bablu', 'Akbar', 'Birbal'],
 'Age': [22, 23, 44, nan],
 'Dept': ['cs', 'AI', 'DS', 'IT'],
 'Salary': [80000, nan, 50000, 60000]}

In [140]:
df = pd.DataFrame(Data)
df

     Name   Age Dept   Salary
0   Vivek  22.0   cs  80000.0
1   Bablu  23.0   AI      NaN
2   Akbar  44.0   DS  50000.0
3  Birbal   NaN   IT  60000.0

In [141]:
print(df.head(3), end='\n\n')
print(df.tail(2))

    Name   Age Dept   Salary
0  Vivek  22.0   cs  80000.0
1  Bablu  23.0   AI      NaN
2  Akbar  44.0   DS  50000.0

     Name   Age Dept   Salary
2   Akbar  44.0   DS  50000.0
3  Birbal   NaN   IT  60000.0

In [142]:
print(df.loc[[0,3], ['Name', 'Dept']], end='\n\n')
print(df.loc[0:3, 'Name'], end='\n\n')
print(df[2:], end='\n\n')

print(df.iloc[0:3, [0, 2]], end='\n\n')
print(df.iloc[[0,2], :3], end='\n\n')
print(df[['Name', "Salary"]], end='\n\n')

     Name Dept
0   Vivek   cs
3  Birbal   IT

0     Vivek
1     Bablu
2     Akbar
3    Birbal
Name: Name, dtype: object

     Name   Age Dept   Salary
2   Akbar  44.0   DS  50000.0
3  Birbal   NaN   IT  60000.0

    Name Dept
0  Vivek   cs
1  Bablu   AI
2  Akbar   DS

    Name   Age Dept
0  Vivek  22.0   cs
2  Akbar  44.0   DS

     Name   Salary
0   Vivek  80000.0
1   Bablu      NaN
2   Akbar  50000.0
3  Birbal  60000.0

In [143]:
df.drop('Age', axis=1)

     Name Dept   Salary
0   Vivek   cs  80000.0
1   Bablu   AI      NaN
2   Akbar   DS  50000.0
3  Birbal   IT  60000.0

In [144]:
df

     Name   Age Dept   Salary
0   Vivek  22.0   cs  80000.0
1   Bablu  23.0   AI      NaN
2   Akbar  44.0   DS  50000.0
3  Birbal   NaN   IT  60000.0

In [145]:
df.drop('Age', axis=1, inplace=True)
df

     Name Dept   Salary
0   Vivek   cs  80000.0
1   Bablu   AI      NaN
2   Akbar   DS  50000.0
3  Birbal   IT  60000.0

In [146]:
df = pd.DataFrame(Data)
df

     Name   Age Dept   Salary
0   Vivek  22.0   cs  80000.0
1   Bablu  23.0   AI      NaN
2   Akbar  44.0   DS  50000.0
3  Birbal   NaN   IT  60000.0

In [147]:
print(df.shape)
print(df.ndim)

(4, 4)
2

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     3 non-null      float64
 2   Dept    4 non-null      object
 3   Salary  3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [149]:
df.describe()

             Age        Salary
count   3.000000      3.000000
mean   29.666667  63333.333333
std    12.423097  15275.252317
min    22.000000  50000.000000
25%    22.500000  55000.000000
50%    23.000000  60000.000000
75%    33.500000  70000.000000
max    44.000000  80000.000000

`Broadcasting`

In [150]:
df[['Salary', 'Age']] = df[['Salary', 'Age']] + [5000, 2]
df

     Name   Age Dept   Salary
0   Vivek  24.0   cs  85000.0
1   Bablu  25.0   AI      NaN
2   Akbar  46.0   DS  55000.0
3  Birbal   NaN   IT  65000.0

In [151]:
df.rename(columns={'Dept': 'Department'})

     Name   Age Department   Salary
0   Vivek  24.0         cs  85000.0
1   Bablu  25.0         AI      NaN
2   Akbar  46.0         DS  55000.0
3  Birbal   NaN         IT  65000.0

In [152]:
df

     Name   Age Dept   Salary
0   Vivek  24.0   cs  85000.0
1   Bablu  25.0   AI      NaN
2   Akbar  46.0   DS  55000.0
3  Birbal   NaN   IT  65000.0

In [153]:
df.rename(columns={'Dept': 'Department'}, inplace=True)
df

     Name   Age Department   Salary
0   Vivek  24.0         cs  85000.0
1   Bablu  25.0         AI      NaN
2   Akbar  46.0         DS  55000.0
3  Birbal   NaN         IT  65000.0

In [154]:
df.loc[df['Name'] == 'Bablu', 'Age'] = 24
df

     Name   Age Department   Salary
0   Vivek  24.0         cs  85000.0
1   Bablu  24.0         AI      NaN
2   Akbar  46.0         DS  55000.0
3  Birbal   NaN         IT  65000.0

In [155]:
print(df['Age'].unique())
print(df['Age'].value_counts())

[24. 46. nan]
Age
24.0    2
46.0    1
Name: count, dtype: int64

In [156]:
df['City'] = ['Mumbai', 'Pune', 'Ahilyanagar', 'Ahilyanagar']
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [157]:
print(df.isnull().sum())

Name          0
Age           1
Department    0
Salary        1
City          0
dtype: int64

In [158]:
df.dropna(how = 'any')
# df.dropna(how = 'any', axis=1)
#df.dropna(inplace=True)

    Name   Age Department   Salary         City
0  Vivek  24.0         cs  85000.0       Mumbai
2  Akbar  46.0         DS  55000.0  Ahilyanagar

In [159]:
df.dropna(how='all')

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [160]:
df.fillna(0)

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      0.0         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   0.0         IT  65000.0  Ahilyanagar

In [161]:
print(df['Age'].fillna(df['Age'].mean()))
print(df['Salary'].fillna(df['Salary'].median()))

0    24.000000
1    24.000000
2    46.000000
3    31.333333
Name: Age, dtype: float64
0    85000.0
1    65000.0
2    55000.0
3    65000.0
Name: Salary, dtype: float64

In [162]:
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [163]:
df['Age'].fillna(method = 'ffill')

/tmp/ipykernel_5955/2409552794.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method = 'ffill')

0    24.0
1    24.0
2    46.0
3    46.0
Name: Age, dtype: float64

In [164]:
df['Salary'].fillna(method = 'bfill')

/tmp/ipykernel_5955/1335963949.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary'].fillna(method = 'bfill')

0    85000.0
1    55000.0
2    55000.0
3    65000.0
Name: Salary, dtype: float64

In [165]:
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [166]:
# df.loc[df['Name'] == 'Bablu', 'Age'] = 24
# df['Age'].replace(24, 23)
df[df['Name']=='Bablu'].replace(24, 22)

    Name   Age Department  Salary  City
1  Bablu  22.0         AI     NaN  Pune

In [167]:
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [168]:
demo =pd.DataFrame({ 'Name' : ['Bablu'],'Age':[24], 'Department':['AI'],'Salary':[np.nan], 'City':['Pune']})
df = pd.concat([df, demo], ignore_index=True)

In [169]:
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar
4   Bablu  24.0         AI      NaN         Pune

In [170]:
df[df.duplicated()]
# df[df.duplicated(keep='first')]
# df[df.duplicated(keep='last')]

    Name   Age Department  Salary  City
4  Bablu  24.0         AI     NaN  Pune

In [171]:
df.drop_duplicates(inplace=True)
#df.drop_duplicates(keep='last')
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  55000.0  Ahilyanagar
3  Birbal   NaN         IT  65000.0  Ahilyanagar

In [172]:
df['Salary'] = df['Salary'].apply(lambda x: x+10000 if x < 70000 else x)
df

     Name   Age Department   Salary         City
0   Vivek  24.0         cs  85000.0       Mumbai
1   Bablu  24.0         AI      NaN         Pune
2   Akbar  46.0         DS  65000.0  Ahilyanagar
3  Birbal   NaN         IT  75000.0  Ahilyanagar

In [173]:
demo = pd.Series(['Vivek_Avhad', 'Bablu_Avhad', 'Akbar_Shaikh', 'Birbal_Patil'])
df['Name'] = demo
df

           Name   Age Department   Salary         City
0   Vivek_Avhad  24.0         cs  85000.0       Mumbai
1   Bablu_Avhad  24.0         AI      NaN         Pune
2  Akbar_Shaikh  46.0         DS  65000.0  Ahilyanagar
3  Birbal_Patil   NaN         IT  75000.0  Ahilyanagar

In [174]:
df[['First_Name','Last_Name']] = df['Name'].str.split('_', expand = True)
df

           Name   Age Department   Salary         City First_Name Last_Name
0   Vivek_Avhad  24.0         cs  85000.0       Mumbai      Vivek     Avhad
1   Bablu_Avhad  24.0         AI      NaN         Pune      Bablu     Avhad
2  Akbar_Shaikh  46.0         DS  65000.0  Ahilyanagar      Akbar    Shaikh
3  Birbal_Patil   NaN         IT  75000.0  Ahilyanagar     Birbal     Patil

In [178]:
def square(x):
    return x+5

df['Age'] = df['Age'].apply(square)
df

           Name   Age Department   Salary         City First_Name Last_Name
0   Vivek_Avhad  34.0         cs  85000.0       Mumbai      Vivek     Avhad
1   Bablu_Avhad  34.0         AI      NaN         Pune      Bablu     Avhad
2  Akbar_Shaikh  56.0         DS  65000.0  Ahilyanagar      Akbar    Shaikh
3  Birbal_Patil   NaN         IT  75000.0  Ahilyanagar     Birbal     Patil

In [180]:
df['Age'] = df['Age'].apply(lambda a: a-5)
df

           Name   Age Department   Salary         City First_Name Last_Name
0   Vivek_Avhad  24.0         cs  85000.0       Mumbai      Vivek     Avhad
1   Bablu_Avhad  24.0         AI      NaN         Pune      Bablu     Avhad
2  Akbar_Shaikh  46.0         DS  65000.0  Ahilyanagar      Akbar    Shaikh
3  Birbal_Patil   NaN         IT  75000.0  Ahilyanagar     Birbal     Patil

`Joins and Merges`

In [ ]:
#df.concat()
#df.merge()